name: IKNmapbot

on:
  schedule:
    - cron: '0,30 * * * *'  # once every 30 minutes

jobs:
  IKN-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
      MYMAPPI_PUBLIC_TOKEN: ${{ secrets.MYMAPPI_PUBLIC_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install jsonlite
        run: Rscript -e 'install.packages("jsonlite", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript IKNmapBot-tweet.R
